add_test( [==[EntityID encodes and decodes layer correctly]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[EntityID encodes and decodes layer correctly]==]  )
set_tests_properties( [==[EntityID encodes and decodes layer correctly]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[EntityID null is invalid]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[EntityID null is invalid]==]  )
set_tests_properties( [==[EntityID null is invalid]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[EntityID equality]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[EntityID equality]==]  )
set_tests_properties( [==[EntityID equality]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[EntityID preserves full ID range]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[EntityID preserves full ID range]==]  )
set_tests_properties( [==[EntityID preserves full ID range]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Registry creates entities in correct layers]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Registry creates entities in correct layers]==]  )
set_tests_properties( [==[Registry creates entities in correct layers]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Registry add and get components]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Registry add and get components]==]  )
set_tests_properties( [==[Registry add and get components]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Registry destroy entity]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Registry destroy entity]==]  )
set_tests_properties( [==[Registry destroy entity]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Registry iterate all entities with components]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Registry iterate all entities with components]==]  )
set_tests_properties( [==[Registry iterate all entities with components]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Registry iterate entities in specific layer]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Registry iterate entities in specific layer]==]  )
set_tests_properties( [==[Registry iterate entities in specific layer]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Registry entity count per layer]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Registry entity count per layer]==]  )
set_tests_properties( [==[Registry entity count per layer]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Registry remove component]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Registry remove component]==]  )
set_tests_properties( [==[Registry remove component]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[EventBus emit and dispatch]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[EventBus emit and dispatch]==]  )
set_tests_properties( [==[EventBus emit and dispatch]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[EventBus layer targeting]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[EventBus layer targeting]==]  )
set_tests_properties( [==[EventBus layer targeting]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[EventBus broadcast reaches all layers]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[EventBus broadcast reaches all layers]==]  )
set_tests_properties( [==[EventBus broadcast reaches all layers]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[EventBus events are logged]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[EventBus events are logged]==]  )
set_tests_properties( [==[EventBus events are logged]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[EventBus events dispatched in timestamp order]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[EventBus events dispatched in timestamp order]==]  )
set_tests_properties( [==[EventBus events dispatched in timestamp order]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[EventLog query by time range]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[EventLog query by time range]==]  )
set_tests_properties( [==[EventLog query by time range]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[EventLog truncate_after]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[EventLog truncate_after]==]  )
set_tests_properties( [==[EventLog truncate_after]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[EventBus multiple handlers for same type]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[EventBus multiple handlers for same type]==]  )
set_tests_properties( [==[EventBus multiple handlers for same type]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[RNG determinism - same seed same sequence]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[RNG determinism - same seed same sequence]==]  )
set_tests_properties( [==[RNG determinism - same seed same sequence]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[RNG different seeds produce different sequences]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[RNG different seeds produce different sequences]==]  )
set_tests_properties( [==[RNG different seeds produce different sequences]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[RNG float range]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[RNG float range]==]  )
set_tests_properties( [==[RNG float range]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[RNG float range with min/max]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[RNG float range with min/max]==]  )
set_tests_properties( [==[RNG float range with min/max]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[RNG int range]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[RNG int range]==]  )
set_tests_properties( [==[RNG int range]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[RNG split produces independent streams]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[RNG split produces independent streams]==]  )
set_tests_properties( [==[RNG split produces independent streams]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[RNG split is deterministic]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[RNG split is deterministic]==]  )
set_tests_properties( [==[RNG split is deterministic]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[BinaryStream round-trip integers]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[BinaryStream round-trip integers]==]  )
set_tests_properties( [==[BinaryStream round-trip integers]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[BinaryStream round-trip floats]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[BinaryStream round-trip floats]==]  )
set_tests_properties( [==[BinaryStream round-trip floats]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[BinaryStream round-trip strings]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[BinaryStream round-trip strings]==]  )
set_tests_properties( [==[BinaryStream round-trip strings]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[BinaryStream file round-trip]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[BinaryStream file round-trip]==]  )
set_tests_properties( [==[BinaryStream file round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[BinaryReader throws on read past end]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[BinaryReader throws on read past end]==]  )
set_tests_properties( [==[BinaryReader throws on read past end]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[BinaryStream raw bytes round-trip]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[BinaryStream raw bytes round-trip]==]  )
set_tests_properties( [==[BinaryStream raw bytes round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[SimTime unit conversions]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[SimTime unit conversions]==]  )
set_tests_properties( [==[SimTime unit conversions]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[SimTime arithmetic]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[SimTime arithmetic]==]  )
set_tests_properties( [==[SimTime arithmetic]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[SimTime comparison]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[SimTime comparison]==]  )
set_tests_properties( [==[SimTime comparison]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[TickScheduler ticks layers at correct level]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[TickScheduler ticks layers at correct level]==]  )
set_tests_properties( [==[TickScheduler ticks layers at correct level]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[TickScheduler advances time correctly]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[TickScheduler advances time correctly]==]  )
set_tests_properties( [==[TickScheduler advances time correctly]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[TickScheduler pause prevents ticking]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[TickScheduler pause prevents ticking]==]  )
set_tests_properties( [==[TickScheduler pause prevents ticking]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[TickScheduler dispatches events after tick]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[TickScheduler dispatches events after tick]==]  )
set_tests_properties( [==[TickScheduler dispatches events after tick]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Full simulation lifecycle]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Full simulation lifecycle]==]  )
set_tests_properties( [==[Full simulation lifecycle]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Snapshot save and load]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Snapshot save and load]==]  )
set_tests_properties( [==[Snapshot save and load]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Cross-layer events are delivered]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Cross-layer events are delivered]==]  )
set_tests_properties( [==[Cross-layer events are delivered]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Different tick levels activate correct layers]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Different tick levels activate correct layers]==]  )
set_tests_properties( [==[Different tick levels activate correct layers]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Perlin noise is deterministic]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Perlin noise is deterministic]==]  )
set_tests_properties( [==[Perlin noise is deterministic]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Perlin noise output range is bounded]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Perlin noise output range is bounded]==]  )
set_tests_properties( [==[Perlin noise output range is bounded]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Perlin fbm returns normalised range]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Perlin fbm returns normalised range]==]  )
set_tests_properties( [==[Perlin fbm returns normalised range]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Different seeds produce different noise]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Different seeds produce different noise]==]  )
set_tests_properties( [==[Different seeds produce different noise]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Heightmap basic operations]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Heightmap basic operations]==]  )
set_tests_properties( [==[Heightmap basic operations]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Heightmap normalise]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Heightmap normalise]==]  )
set_tests_properties( [==[Heightmap normalise]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Heightmap bilinear sampling]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Heightmap bilinear sampling]==]  )
set_tests_properties( [==[Heightmap bilinear sampling]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Heightmap serialisation round-trip]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Heightmap serialisation round-trip]==]  )
set_tests_properties( [==[Heightmap serialisation round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Biome: deep ocean classification]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Biome: deep ocean classification]==]  )
set_tests_properties( [==[Biome: deep ocean classification]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Biome: the deep ocean boundary is exclusive]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Biome: the deep ocean boundary is exclusive]==]  )
set_tests_properties( [==[Biome: the deep ocean boundary is exclusive]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Biome: desert at high temp low moisture]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Biome: desert at high temp low moisture]==]  )
set_tests_properties( [==[Biome: desert at high temp low moisture]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Biome: tropical rainforest at high temp high moisture]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Biome: tropical rainforest at high temp high moisture]==]  )
set_tests_properties( [==[Biome: tropical rainforest at high temp high moisture]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Biome: tundra at cold temperatures]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Biome: tundra at cold temperatures]==]  )
set_tests_properties( [==[Biome: tundra at cold temperatures]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Biome: mountain at high elevation]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Biome: mountain at high elevation]==]  )
set_tests_properties( [==[Biome: mountain at high elevation]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Biome: beach near sea level]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Biome: beach near sea level]==]  )
set_tests_properties( [==[Biome: beach near sea level]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Terrain generator produces valid heightmap]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Terrain generator produces valid heightmap]==]  )
set_tests_properties( [==[Terrain generator produces valid heightmap]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Terrain generator is deterministic]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Terrain generator is deterministic]==]  )
set_tests_properties( [==[Terrain generator is deterministic]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Terrain has both land and ocean]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Terrain has both land and ocean]==]  )
set_tests_properties( [==[Terrain has both land and ocean]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Temperature is cold at poles, warm at equator]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Temperature is cold at poles\, warm at equator]==]  )
set_tests_properties( [==[Temperature is cold at poles, warm at equator]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[Moisture decreases inland]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[Moisture decreases inland]==]  )
set_tests_properties( [==[Moisture decreases inland]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
add_test( [==[PlanetData serialisation round-trip]==] /Users/mehmetisitmen/dev/God-Simulation/build-rend/godsim_tests [==[PlanetData serialisation round-trip]==]  )
set_tests_properties( [==[PlanetData serialisation round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/mehmetisitmen/dev/God-Simulation/build-rend)
set( godsim_tests_TESTS [==[EntityID encodes and decodes layer correctly]==] [==[EntityID null is invalid]==] [==[EntityID equality]==] [==[EntityID preserves full ID range]==] [==[Registry creates entities in correct layers]==] [==[Registry add and get components]==] [==[Registry destroy entity]==] [==[Registry iterate all entities with components]==] [==[Registry iterate entities in specific layer]==] [==[Registry entity count per layer]==] [==[Registry remove component]==] [==[EventBus emit and dispatch]==] [==[EventBus layer targeting]==] [==[EventBus broadcast reaches all layers]==] [==[EventBus events are logged]==] [==[EventBus events dispatched in timestamp order]==] [==[EventLog query by time range]==] [==[EventLog truncate_after]==] [==[EventBus multiple handlers for same type]==] [==[RNG determinism - same seed same sequence]==] [==[RNG different seeds produce different sequences]==] [==[RNG float range]==] [==[RNG float range with min/max]==] [==[RNG int range]==] [==[RNG split produces independent streams]==] [==[RNG split is deterministic]==] [==[BinaryStream round-trip integers]==] [==[BinaryStream round-trip floats]==] [==[BinaryStream round-trip strings]==] [==[BinaryStream file round-trip]==] [==[BinaryReader throws on read past end]==] [==[BinaryStream raw bytes round-trip]==] [==[SimTime unit conversions]==] [==[SimTime arithmetic]==] [==[SimTime comparison]==] [==[TickScheduler ticks layers at correct level]==] [==[TickScheduler advances time correctly]==] [==[TickScheduler pause prevents ticking]==] [==[TickScheduler dispatches events after tick]==] [==[Full simulation lifecycle]==] [==[Snapshot save and load]==] [==[Cross-layer events are delivered]==] [==[Different tick levels activate correct layers]==] [==[Perlin noise is deterministic]==] [==[Perlin noise output range is bounded]==] [==[Perlin fbm returns normalised range]==] [==[Different seeds produce different noise]==] [==[Heightmap basic operations]==] [==[Heightmap normalise]==] [==[Heightmap bilinear sampling]==] [==[Heightmap serialisation round-trip]==] [==[Biome: deep ocean classification]==] [==[Biome: the deep ocean boundary is exclusive]==] [==[Biome: desert at high temp low moisture]==] [==[Biome: tropical rainforest at high temp high moisture]==] [==[Biome: tundra at cold temperatures]==] [==[Biome: mountain at high elevation]==] [==[Biome: beach near sea level]==] [==[Terrain generator produces valid heightmap]==] [==[Terrain generator is deterministic]==] [==[Terrain has both land and ocean]==] [==[Temperature is cold at poles, warm at equator]==] [==[Moisture decreases inland]==] [==[PlanetData serialisation round-trip]==])
